### ISSUE TITLE
Make burn and mint methods accept references of the BucketRef ?

### ISSUE THREAD

**Issue by cbisaillon** [radixdlt/radixdlt-scrypto#65] opened 2021-11-27 19:00 UTC
I see that it is not possible to burn two different tokens with the same badge in a `authorize` block. 
Maybe making `mint` and `burn` methods accept a reference to a BucketRef would solve the issue ?

```
pub fn change_supply(&mut self, badge_to_burn: Bucket) {
    self.minter_badge.authorize(|badge| {
        badge_to_burn.burn(badge);
        // todo: error here: use of moved resource: badge
        self.token_vault.take(100).burn(badge);
    });
}
```

**Comment by iamyulong** [comment] 2021-11-29 12:17
We're working on our new resource model. You should be able to configure every aspect of resource, including burning. Stay tuned. :)

**Comment by devmannic** [comment] 2021-12-06 17:12
I think this could be related to this issue, so mentioning it here (but sorry don't mean to hijack).

Currently a `BucketRef` cannot easily be passed between functions.  This is because `BucketRef` is not `Copy` (even though `Rid` *is* and `BucketRef is just a wrapper for it).  Is this an oversight or by design?  The place this came up is It makes it impossible to use a BucketRef received in one function (such as when using `#[auth]`) and then passing it to another function where minting or burning might happen for example.

**Comment by iamyulong** [comment] 2021-12-06 17:31
`BucketRef` is not copyable mainly because it represents a specific bucket reference, managed by the runtime.  When you call a function with BucketRef, it will be moved to the callee.

It has the same semantics as Rust (although different syntax from Rust):
```
let a = 1u8;
let b = &a;   // b is one reference
let c = &a;   // c is another reference
```

However, the following is not allowed currently
```
let a = 1u8;
let b = &a;
let c = &b; // This is not allowed when using BucketRef
```

Still debating whether we should allow the above operations.

**Comment by devmannic** [comment] 2021-12-07 03:01
That makes sense.  Thanks.  I think without changing then options become limited for how to work with a single `BucketRef` which is intended to both authorize access to a function, and then be used more than once since all the operations currently do a move.  I guess a work around would be make a transaction with the same bucket twice so that RE creates 2 BucketRefs, one for use as `auth` and then one for a "free" argument.  This is similar in concept to the `authorize2` suggestion above.  Though I'm not sure that's a great solution, it does aligns with the existing semantics and seems like it would be ok.  Probably just needs some more documentation if that is the expected pattern.

Actually maybe a better answer to both these concerns is to have a version of mint/burn (and indeed anything that takes a BucketRef) which also returns the BucketRef instead of "losing" it.  Then you could use that version when you only have a BucketRef instead of doing a borrow on a `Bucket`.  What do you think of that?  It avoids changing (directly or indirectly) the semantics for BucketRef (I think).

**Comment by iamyulong** [comment] 2021-12-07 09:33
Providing another flavour of system functions that return the bucket rather than drop it is an interesting idea. This is also similar to how the `#auth(keep_auth)` works in component method authorisation check.

Can't give you a definite answer now but I will put more thoughts on it.

**Comment by iamyulong** [comment] 2021-12-09 21:43
Per https://github.com/radixdlt/radixdlt-scrypto/commit/8e56cb72d6d1d130c55c6dc453f5514c549fa5ac, we're now allowed to clone `BucketRef`.

**Comment by devmannic** [comment] 2021-12-09 21:49
Thanks for the follow up.  hat looks good.  I think that solves all the problems in this issue, right @cbisaillon  ?

**Comment by cbisaillon** [comment] 2021-12-10 15:37
It now works, but I have to wrap the BucketRef in an Option in the burn method. Is this intended ? It feels weird to have to do this for the burn, but not for the mint. What do you think ?
![image](https://user-images.githubusercontent.com/4528924/145600249-d8c8001c-a39a-4908-b6c6-d4f1e55d5392.png)

**Comment by devmannic** [comment] 2021-12-10 16:06
It's because you can make a resource that anyone can burn without a badge, and since Rust doesn't do overloaded functions, this is how that's handled.  I'm not sure why mint isn't the same way.  I would have thought if you can make a resource without authorizing a badge then it could also be minted freely.  (again, not sure the use case of this either).

In any case, I don't really like the Option arguments as the main API.  It's harder to read.  BUT it is better for static analysis, and I like that.  But, if we prioritize developers higher then I'd much rather see the following builder pattern API.  It's more readable and consistent.

```rust
staker_badge.resource_def().authorize(minter).mint(1);
// or even
staker_badge.resource_def().authorize(minter, MINT).mint(1);
// and also
staker_badge.burn()
// or
staker_badge.authorize().burn()
// or even
staker_badge.authorize(BURN).burn()
```

These require some new intermediate types though I think.

**Comment by iamyulong** [comment] 2021-12-10 16:35
@cbisaillon @devmannic do you think it would be better to have two `burn` APIs, instead of an optional argument?
```
bucket.burn();
bucket.burn_with_auth(some_bucket_ref);
```
With the latest `RESTRICTED_TRANSFER`, we already have:
```
vault.take(5);
vault.take_with_auth(5, some_bucket_ref);
```

**Comment by devmannic** [comment] 2021-12-10 16:40
That looks great. I think those 2 APIs would be much better.  And particularly since the `take_with_auth` already exists (which I didn't realize) this is a nice complement keeping things as consistent as possible. -- It does making some programming patterns more verbose when the `Option` is not available, but I think realistically it's much much more readable/usable with this proposed API instead.

**Comment by cbisaillon** [comment] 2021-12-10 16:41
@iamyulong Good idea !

**Comment by iamyulong** [comment] 2021-12-10 16:43
Thanks! Will make the change shortly.

**Comment by 0xOmarA** [comment] 2022-07-17 21:54
Closing this issue since the `mint` and `burn` methods on the `ResourceManager` no longer require a `Proof` to be passed by intent. Instead, we have switched to a new system-level authorization system.

**Closed by 0xOmarA** 2022-07-17 21:54 UTC
Labels: question
