### ISSUE TITLE
Issue when dividing negative Decimal

### ISSUE THREAD

**Issue by cbisaillon** [radixdlt/radixdlt-scrypto#92] opened 2021-12-11 20:17 UTC
I get weird results when dividing a negative Decimal:

code:
```
let a: Decimal = (-42).into();
info!("a: {}", a);
info!("a / 2: {}", a / 2);
```

result:
![image](https://user-images.githubusercontent.com/4528924/145690425-6eed0d08-0b1e-433e-8ea3-a6d72cfa82ab.png)

**Comment by devmannic** [comment] 2021-12-11 22:03
I can confirm this is a bug.  The error is here:

https://github.com/radixdlt/radixdlt-scrypto/blob/main/scrypto/src/types/decimal.rs#L128

This way of copying back to Decimal is unnecessarily complicated.  I'd suggest looking at my example in #93 which uses the `ToPrimitive` trait instead (though you still need to extend it to check the Option for implied overflow and handle PRECISION)

When I was figuring out the best ways to convert between BigInt and Decimal I hit a similar bug.  I believe the issue is creating the 16 byte array of 0x01 and then copying the slice.  The problem is the source for that copy (ie `bytes`) may be less than 16 bytes (it depends on the size of the BigInt) and so those high bits are not properly cleared.  You could patch it up, but I think the `ToPrimitive` method is better.  I also ran into floating point issues uses the num-bigint even with `std` disabled when using some of the conversion functions.  `to_i128` seems better all around

**Comment by iamyulong** [comment] 2021-12-14 19:38
Fix merged into develop branch

**Closed by iamyulong** 2021-12-14 19:38 UTC
Labels: bug
